
---
# --- TASK1 Deployment ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task1
  template:
    metadata:
      labels:
        app: task1
    spec:
      containers:
      - name: app
        image: bistrulli/generic-microservice-tester:0.6
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "1000m"
            memory: "1536Mi"
          limits:
            cpu: "3000m"
            memory: "1536Mi"
        env:
        - name: SERVICE_NAME
          value: "task1"
        - name: SERVICE_TIME_SECONDS
          value: "0.5"
        - name: OUTBOUND_CALLS
          value: "SYNC:task2-svc:0.5,SYNC:task3-svc:0.5"
        - name: GUNICORN_WORKERS
          value: "10"
        - name: GUNICORN_THREADS
          value: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: task1-svc
spec:
  selector:
    app: task1
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080

---
# --- Istio DestinationRule for TASK1 ---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: task1-random-lb
spec:
  host: task1-svc
  trafficPolicy:
    loadBalancer:
      simple: RANDOM

---
# --- TASK2 Deployment ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task2
  template:
    metadata:
      labels:
        app: task2
    spec:
      containers:
      - name: app
        image: bistrulli/generic-microservice-tester:0.6
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "1000m"
            memory: "1536Mi"
          limits:
            cpu: "3000m"
            memory: "1536Mi"
        env:
        - name: SERVICE_NAME
          value: "task2"
        - name: SERVICE_TIME_SECONDS
          value: "0.1"
        - name: OUTBOUND_CALLS
          value: "SYNC:task3-svc:1.0"
        - name: GUNICORN_WORKERS
          value: "10"
        - name: GUNICORN_THREADS
          value: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: task2-svc
spec:
  selector:
    app: task2
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080

---
# --- Istio DestinationRule for TASK2 ---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: task2-random-lb
spec:
  host: task2-svc
  trafficPolicy:
    loadBalancer:
      simple: RANDOM

---
# --- TASK3 Deployment ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task3-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task3
  template:
    metadata:
      labels:
        app: task3
    spec:
      containers:
      - name: app
        image: bistrulli/generic-microservice-tester:0.6
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "1000m"
            memory: "1536Mi"
          limits:
            cpu: "3000m"
            memory: "1536Mi"
        env:
        - name: SERVICE_NAME
          value: "task3"
        - name: SERVICE_TIME_SECONDS
          value: "0.15"
        - name: OUTBOUND_CALLS
          value: ""
        - name: GUNICORN_WORKERS
          value: "10"
        - name: GUNICORN_THREADS
          value: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: task3-svc
spec:
  selector:
    app: task3
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080

---
# --- Istio DestinationRule for TASK3 ---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: task3-random-lb
spec:
  host: task3-svc
  trafficPolicy:
    loadBalancer:
      simple: RANDOM

---